# Generated by Django 5.0.3 on 2024-06-05 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='p_id',
            field=models.CharField(default='a', max_length=100),
        ),
    ]
