# Generated by Django 5.0.3 on 2024-06-08 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_cart_p_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='p_id',
        ),
    ]
